name: simple_form
description: "A new Flutter package project."
version: 0.0.1
homepage: https://github.com/koiralapankaj7/simple_form.git
publish_to: none

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  collection: ^1.19.0
  collection_view:
    path: ../collection_view
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0

flutter:
  assets:
    - json/countries.json
